version: '3.8'
services:
  db:
    image: postgres:15
    container_name: license_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licenses_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: ./app
    container_name: license_server
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://myuser:mypassword@db:5432/licenses_db"
      PRIVATE_KEY_PATH: "/app/keys/private_key.pem"
      PUBLIC_KEY_PATH: "/app/keys/public_key.pem"
      SECRET_KEY: "your_secret_key"
    volumes:
      - ./app/keys:/app/keys
    depends_on:
      - db
    ports:
      - "8000:8000"