version: "3.9"

services:
  db:
    image: postgres:15
    container_name: license_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: licenses_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -h db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: license_server
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://myuser:mypassword@db:5432/licenses_db"
      SECRET_KEY: "your_secret_key"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"